### PR TITLE
feat: swarm

### PR DESCRIPTION
**Pull request by nugaon**
the built app is compatible with the [Swarm ecosystem](https://docs.ethswarm.org/docs/)

### CODE REVIEW

**Comment by nugaon** [comment]
sorry, bad base

**Comment by begleysm** [comment]
@nugaon embarrassingly, I was not getting emails about PRs and so I'm just now seeing this a year later...  Let me know if you still have work you'd like to share.

**Comment by nugaon** [comment]
hey @begleysm , I just had a quick 1-2 hours hacking on your project, because I was curious whether Quake3 can be served by decentralized storage client like [Ethereum Swarm](https://www.ethswarm.org/).

The mini-project was successful and the whole game could be uploaded to the Swarm network for which [I had to make just subtle changes](https://github.com/nugaon/quakejs/tree/feat/swarm), (though it should be refactored).

As I remember, I had some problem with reaching out online matchmaking if the client was served with `http://` because of [mixed content](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content). It is not the problem of the repo, it is just the nature of the storage clients that usually do not have SSL/TLS key for secure API communication except ofc if those are Public Gateways.

**Comment by begleysm** [comment]
@nugaon roger.  There have been some updates since, one of which is directly related to secure server `https://` and `wss://` access.  Some of the issues you had to work through may have been handled by PR https://github.com/begleysm/quakejs/pull/15.  Just submit another PR if you have any more work you'd like to share.  I have email alerts activated now so it shouldn't take a year for me to see it this time lol

**Pull request closed without merging**
